# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-ecs-cluster
  description: Terraform module for provisioning an ECS cluster
  homepage: https://cloudposse.com/accelerate
  topics: ""
